.travis.yml
- https://github.com/metanorma/metanorma-standoc/pull/50#issuecomment-473736044
=> Use metanorma-linux-setup script to configure VM

.tex, README.adoc, appveyor.yml, lib/asciidoctor/standoc/inline.rb
- https://github.com/metanorma/metanorma-standoc/issues/55
=> Add appvyor config

appveyor.yml, lib/asciidoctor/standoc/inline.rb
- https://github.com/metanorma/metanorma-standoc/issues/60
=> Move back to latexmlmath from latexmlc

lib/asciidoctor/standoc/inline.rb
- https://github.com/metanorma/homebrew-metanorma/pull/12
=> Specify encoding explicitly during for popen latexmlmath

Gemfile
- from https://github.com/metanorma/metanorma-standoc/pull/64
- https://github.com/metanorma/metanorma-standoc/issues/65
=> Use newest VCR form git

Gemfile, Gemfile.lock, metanorma-standoc.gemspec
- https://github.com/metanorma/metanorma-standoc/issues/67
=> Move to vcr 5.0.0 from rubygems

lib/asciidoctor/standoc/validate.rb
=> #86 Improve error message for Jing

.travis.yml, appveyor.yml, lib/asciidoctor/standoc/inline.rb, lib/metanorma/standoc.rb, lib/metanorma/standoc/latexml_requirement.rb, lib/metanorma/standoc/processor.rb, lib/metanorma/standoc/requirement.rb
=> #60 add --inputencoding param to latexmlmath, which was introduced in LaTeXML@0.8.4

.travis.yml, appveyor.yml, lib/asciidoctor/standoc/macros.rb, lib/metanorma/standoc/latexml_requirement.rb, lib/metanorma/standoc/processor.rb
=> #96 do lazy latexml check

.travis.yml, appveyor.yml, lib/asciidoctor/standoc/macros.rb, lib/metanorma/standoc/latexml_requirement.rb, lib/metanorma/standoc/processor.rb
Reverts metanorma/metanorma-standoc#98
=> Revert "#96 do lazy latexml check"

lib/metanorma/standoc/latexml_requirement.rb, lib/metanorma/standoc/processor.rb
- https://github.com/metanorma/metanorma-standoc/issues/101
=> Add accurate soft error message

lib/asciidoctor/standoc/base.rb, lib/asciidoctor/standoc/macros.rb, spec/asciidoctor-standoc/macros_spec.rb
=> Add html5rubymacro asciidoctor extension support

.github/workflows/macos.yml, .github/workflows/ubuntu.yml, .github/workflows/windows.yml
- https://github.com/metanorma/metanorma-standoc/issues/206
- https://github.com/metanorma/ci-master/issues/1
=> Update GH workflows

.github/workflows/macos.yml
=> #235 freeze LibXML version for OSX

.github/workflows/ubuntu.yml
As title. 
_Generated by Cimas_.
=> Add libgbm1 installation for pupeteer & update python to 3.6

lib/asciidoctor/standoc/base.rb, spec/asciidoctor-standoc/validate_spec.rb
=> #236 fix for error log Errno::ENOENT

lib/asciidoctor/standoc/macros_yaml2text.rb, lib/asciidoctor/standoc/views/datamodel/model_representation.adoc.erb, spec/asciidoctor-standoc/datamodel/attributes_table_preprocessor_spec.rb, spec/examples/datamodel/blank_definition_profile.adoc, spec/examples/datamodel/models/models/SignatureBlankDefinition.yml, spec/fixtures/macros_datamodel/blank_definition_profile.xml
metanorma/metanorma-standoc#292 explicit yaml2text warning on error, fix definition datamodel error
=> Explicit yaml2text error warnings, datamodel blank definition crash fix

lib/asciidoctor/standoc/json2_text_preprocessor.rb, lib/asciidoctor/standoc/yaml2_text_preprocessor.rb
#346 read all files with utf-8 encoding, yaml2text/json2text
=> yaml2text read all files in utf-8

lib/asciidoctor/standoc/base_structured_text_preprocessor.rb, lib/liquid/custom_blocks/with_json_nested_context.rb, lib/liquid/custom_blocks/with_yaml_nested_context.rb, spec/support/shared_examples/structured_data_2_text_preprocessor.rb
#347 support for nested yaml2text/json2text blocks, custom liquid tags: with_yaml_nested_context, with_json_nested_context, new specs for nested case
=> yaml2text nested macroses support

lib/asciidoctor/standoc/converter.rb, metanorma-standoc.gemspec
=> #375 add fontist for required font installation

lib/asciidoctor/standoc/converter.rb, metanorma-standoc.gemspec, spec/asciidoctor-standoc/converter_spec.rb
=> #375 migrate to Fontist::Install.from_hash API

lib/asciidoctor/standoc/cleanup_inline.rb
metanorma/metanorma#142 expose method Asciidoctor::Standoc::Cleanup.to_ncname, needed for metanorma/metanorma#150
=> Expose method Asciidoctor::Standoc::Cleanup.to_ncname

lib/asciidoctor/standoc/converter.rb, spec/asciidoctor/macros_plantuml_spec.rb
https://github.com/metanorma/metanorma-plugin-lutaml/pull/36
=> Use Metanorma::Plugin::Lutaml::LutamlDiagramBlockMacro as a block macro

lib/asciidoctor/standoc/validate.rb
- :negative_squared_cross_mark: Breaking changes (list related PRs)
- :negative_squared_cross_mark: Documentation update required ([create task for this](https://github.com/metanorma/metanorma.org/issues/new))
- :negative_squared_cross_mark: External dependency introduced ([documentation update need](https://github.com/metanorma/metanorma.org/issues/new))
- :negative_squared_cross_mark: Gem with native library introduced
=> #539 explicitly set encoding to UTF-8 for jing

lib/asciidoctor/standoc/base.rb, lib/asciidoctor/standoc/render.rb
=> PDF encryption: https://github.com/metanorma/metanorma/issues/224

lib/asciidoctor/standoc/isodoc.rng, lib/asciidoctor/standoc/section.rb, spec/asciidoctor/section_spec.rb
=> floating titles: https://github.com/metanorma/metanorma-bsi/issues/82

lib/asciidoctor/standoc/cleanup.rb, lib/asciidoctor/standoc/cleanup_section.rb, lib/asciidoctor/standoc/isodoc.rng, lib/asciidoctor/standoc/section.rb, spec/asciidoctor/section_spec.rb
=> floating title: https://github.com/metanorma/metanorma-bsi/issues/95

lib/asciidoctor/standoc/base.rb, lib/asciidoctor/standoc/cleanup.rb, lib/asciidoctor/standoc/cleanup_toc.rb, spec/asciidoctor/base_spec.rb, spec/asciidoctor/refs_spec.rb
=> toc metadata: https://github.com/metanorma/metanorma/issues/226

.github/workflows/rake.yml, spec/asciidoctor/base_spec.rb, spec/asciidoctor/cleanup_spec.rb, spec/asciidoctor/cleanup_terms_spec.rb
As title. 
_Generated by Cimas_.
=> metanorma/metanorma-build-scripts#71 Update workflow to include shared one

lib/metanorma/standoc/converter.rb, lib/metanorma/standoc/macros_terms.rb, spec/metanorma/cleanup_terms_spec.rb, spec/metanorma/macros_spec.rb
=> admitted:[] macro: https://github.com/metanorma/metanorma-ogc/issues/339

lib/metanorma/standoc/inline.rb, lib/metanorma/standoc/isodoc.rng, spec/metanorma/inline_spec.rb
=> span/style: https://github.com/metanorma/metanorma-standoc/issues/647

lib/metanorma/standoc/blocks.rb, lib/metanorma/standoc/cleanup_maths.rb, lib/metanorma/standoc/cleanup_symbols.rb, lib/metanorma/standoc/cleanup_text.rb, lib/metanorma/standoc/cleanup_xref.rb, lib/metanorma/standoc/converter.rb, lib/metanorma/standoc/front.rb, lib/metanorma/standoc/inline.rb, lib/metanorma/standoc/ref_sect.rb, lib/metanorma/standoc/ref_utility.rb, lib/metanorma/standoc/reqt.rb
=> refactor HTMLEntities calls

lib/metanorma/standoc/macros_inline.rb, spec/metanorma/biblio_spec.rb, spec/metanorma/macros_spec.rb
=> span macro rename: https://github.com/metanorma/metanorma-iso/issues/759

lib/metanorma/standoc/blocks.rb, spec/metanorma/blocks_spec.rb
=> figure classes: https://github.com/metanorma/metanorma-standoc/issues/74

lib/metanorma/standoc/macros_plantuml.rb
- metanorma/metanorma-utils#20
Implementation details:
Correct binary to use on windows is `plantumlc` instead `plantuml` more details https://github.com/majkinetor/au-packages/tree/master/plantuml#notes
=> metanorma/metanorma-utils#20 use correct binary for PlantUML on Windows

lib/metanorma/standoc/base.rb, lib/metanorma/standoc/cleanup_inline.rb, lib/metanorma/standoc/inline.rb, spec/metanorma/inline_spec.rb
=> xref/@style: https://github.com/metanorma/metanorma-ogc/issues/330

lib/metanorma/standoc/isodoc.rng, lib/metanorma/standoc/macros_terms.rb, spec/metanorma/macros_concept_spec.rb
=> concept/@bold: https://github.com/metanorma/metanorma-bsi/issues/162

lib/metanorma/standoc/ref_sect.rb, spec/metanorma/refs_spec.rb
=> DOI integration: https://github.com/metanorma/metanorma-ogc/issues/431

.github/workflows/rake.yml
=> #676 move out plantuml workflow

.github/workflows/rake.yml
=> This reverts commit de69f38fb4bebb26d0ab46ad1307c5d1c8d2cf41.

lib/metanorma/standoc/cleanup_section.rb, lib/metanorma/standoc/isodoc.rng, lib/metanorma/standoc/section.rb, spec/metanorma/section_spec.rb
=> colophon: https://github.com/metanorma/metanorma-bsi/issues/241

lib/metanorma/standoc/converter.rb, lib/metanorma/standoc/macros.rb, metanorma-standoc.gemspec
Adding support for `metanorma-plugin-glossarist` macros in Metanorma.
=> feat: adding support for glossarist plugin

lib/metanorma/standoc/cleanup_inline.rb, spec/metanorma/cleanup_spec.rb, spec/metanorma/validate_spec.rb
=> https://github.com/metanorma/metanorma/issues/306

Gemfile
=> Simplify gem_eval call in Gemfile

lib/metanorma-standoc.rb, lib/metanorma/standoc/cleanup_image.rb, lib/metanorma/standoc/inline.rb, lib/metanorma/standoc/validate.rb, metanorma-standoc.gemspec
See https://github.com/metanorma/metanorma-utils/issues/27
=> Integrate Vectory

lib/metanorma/standoc/anchor.rb, lib/metanorma/standoc/cleanup_inline.rb, lib/metanorma/standoc/isodoc.rng, spec/metanorma/inline_spec.rb
=> link/style: https://github.com/metanorma/metanorma-ietf/issues/95

lib/metanorma/standoc/basicdoc.rng, lib/metanorma/standoc/blocks_notes.rb, lib/metanorma/standoc/section.rb, lib/metanorma/standoc/term_lookup_cleanup.rb, spec/metanorma/blocks_spec.rb, spec/metanorma/macros_spec.rb
=> review/type: https://github.com/metanorma/mn-samples-bsi/issues/312

lib/metanorma/standoc/cleanup.rb, lib/metanorma/standoc/ref_utility.rb
=> https://github.com/metanorma/metanorma-standoc/issues/862

lib/metanorma/standoc/converter.rb
=> Register extension Metanorma::Plugin::Lutaml::LutamlEaDiagramBlockMacro

lib/metanorma/standoc/base.rb, lib/metanorma/standoc/cleanup_inline.rb, lib/metanorma/standoc/cleanup_text.rb, lib/metanorma/standoc/datamodel/plantuml_renderer.rb, lib/metanorma/standoc/localbib.rb, lib/metanorma/standoc/macros.rb, lib/metanorma/standoc/macros_plantuml.rb, lib/metanorma/standoc/ref.rb, lib/metanorma/standoc/ref_utility.rb, lib/metanorma/standoc/section.rb, spec/metanorma/base_spec.rb
=> security updates

lib/metanorma/standoc/converter.rb
=> Register extension Metanorma::Plugin::Lutaml::LutamlEaXmiPreprocessor

lib/metanorma/standoc/converter.rb
=> Register extension Metanorma::Plugin::Lutaml::LutamlKlassTableBlockMacro

lib/metanorma/standoc/cleanup_bibdata.rb
=> Speed up resolve_local_indirect_erefs

lib/metanorma/standoc/converter.rb, spec/metanorma/blocks_spec.rb, spec/metanorma/table_spec.rb
=> Register Metanorma::Plugin::Datastruct::Data2TextPreprocessor

Gemfile.devel, lib/metanorma/standoc/base.rb, lib/metanorma/standoc/cleanup_block.rb, lib/metanorma/standoc/cleanup_table.rb, lib/metanorma/standoc/cleanup_terms.rb, lib/metanorma/standoc/cleanup_terms_designations.rb, lib/metanorma/standoc/term_lookup_cleanup.rb, lib/metanorma/standoc/terms.rb, lib/metanorma/standoc/validate_term.rb, spec/metanorma/blocks_spec.rb, spec/metanorma/cleanup_ref_spec.rb, spec/metanorma/cleanup_terms_spec.rb, spec/metanorma/inline_spec.rb
=> termsource to source: https://github.com/metanorma/isodoc/issues/683

lib/metanorma/standoc/cleanup_boilerplate.rb
=> Limit the occurrence of the regex pattern

lib/metanorma/standoc/converter.rb
=> Register LutamlEnumTableBlockMacro

lib/metanorma/standoc/converter.rb
=> Register Metanorma::Plugin::Plantuml::ImageBlockMacroProcessor
